server:
  port: 8053

spring:
  application:
    name: erp-order-service
  datasource:
    url: ${DB_URL:jdbc:mysql://prd-db.erp.com:3306/order_db?useSSL=true&serverTimezone=UTC}
    username: ${DB_USERNAME:order_prd}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://prd-eureka.erp.com:8013/eureka/}