server:
  port: 8051

spring:
  application:
    name: erp-product-service
  datasource:
    url: ${DB_URL:jdbc:mysql://test-db.erp.com:3306/product_db?useSSL=true&serverTimezone=UTC}
    username: ${DB_USERNAME:product_test}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  # Configuration AWS S3
  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET_NAME:erp-app-uploads}
        region: ${AWS_S3_REGION:eu-west-3}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:}
        secret-key: ${AWS_SECRET_ACCESS_KEY:}
      region:
        static: ${AWS_S3_REGION:eu-west-3}
# Configuration for file upload
file:
  upload:
    local:
      directory: uploads
    s3:
      bucket: ${AWS_S3_BUCKET_NAME:erp-app-uploads}
      region: ${AWS_S3_REGION:eu-west-3}
      endpoint: ${AWS_S3_ENDPOINT:https://erp-app-uploads.s3.eu-west-3.amazonaws.com}
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://test-eureka.erp.com:8013/eureka/}
