server:
  port: 8058

spring:
  application:
    name: erp-client-service
  datasource:
    url: ${DB_URL:jdbc:mysql://pprd-db.erp.com:3306/client_db?useSSL=true&serverTimezone=UTC}
    username: ${DB_USERNAME:client_pprd}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://pprd-eureka.erp.com:8013/eureka/} 